[package]
name = "mesh_drawing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8", features = [] }
bevy_mod_raycast = "0.6"
bevy_mod_picking = "0.9"
iyes_loopless = { version = "0.7" }
mesh_geometry_utils = { path = "../mesh_geometry_utils" }
