[package]
name = "shape_graphic_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_render",
] }
bevy_transform_gizmo="0.8.0"
editable_shapes_framework={path="../editable_shapes_framework"}